{
 "title": "C-Chain Load",
 "description": "Collection of load testing dashboard set to C chain by default.",
 "tags": [
  "Avalanche",
  "Performance"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "filter" },
   { "name": "datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n  count by (node_id) (\n    rate(avalanche_evm_eth_chain_block_inserts_count[30s]) > 0\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average base fee ",
   "type": "stat",
   "description": "Base fee averaged across all nodes",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "wei" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avalanche_evm_eth_chain_latest_basefee)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Load test metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Issued txs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(load_txs_issued)", "legendFormat": "Confirmed" }
   ]
  },
  {
   "title": "Confirmed txs",
   "type": "stat",
   "description": "Issued transactions which are confirmed and accepted in a block",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(load_txs_confirmed)", "legendFormat": "Confirmed" }
   ]
  },
  {
   "title": "Failed txs",
   "type": "stat",
   "description": "Issued transactions which are confirmed and accepted in a block",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(load_txs_failed)", "legendFormat": "Confirmed" }
   ]
  },
  {
   "title": "In flight txs",
   "type": "stat",
   "description": "Transactions issued but not yet confirmed or failed",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "txs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(load_txs_issued)-sum(load_txs_confirmed)-sum(load_txs_failed)",
     "legendFormat": "Confirmed"
    }
   ]
  },
  {
   "title": "Per second",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "Txs per second",
   "type": "stat",
   "description": "Sum of all current number of transactions processed per second across all nodes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(avalanche_evm_eth_chain_txs_processed[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gas per second",
   "type": "stat",
   "description": "Max gas processed per second across all nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(rate(avalanche_evm_eth_chain_block_gas_used_processed[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blocks per second",
   "type": "stat",
   "description": "Number of blocks produced per second, averaged  across all nodes",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(avalanche_evm_eth_chain_block_inserts[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Per block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Average txs per block",
   "type": "stat",
   "description": "Number of transactions processed per block  averaged across all nodes",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(avalanche_evm_eth_chain_txs_processed[1m])) / avg(rate(avalanche_evm_eth_chain_block_inserts_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average gas per block",
   "type": "stat",
   "description": "Sum of gas used in processed block across all nodes",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(avalanche_evm_eth_chain_block_gas_used_processed[1m])) / avg(rate(avalanche_evm_eth_chain_block_inserts_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average insert time per block",
   "type": "stat",
   "description": "Insert time per block averaged across all nodes",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(rate(avalanche_evm_eth_chain_block_inserts[1m]))/avg(rate(avalanche_evm_eth_chain_block_inserts_count[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}