{
 "title": "Network",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime average",
   "type": "timeseries",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_weighted_average{job=\"avalanchego\"}",
     "legendFormat": "Uptime average {{node_id}}"
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "timeseries",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avalanche_network_node_uptime_rewarding_stake{job=\"avalanchego\"}",
     "legendFormat": "Rewarding stake {{node_id}}"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "timeseries",
   "description": "Number of network peers the node is connected to",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_network_peers{job=\"avalanchego\"}",
     "legendFormat": "Peers connected {{node_id}}"
    }
   ]
  },
  {
   "title": "Network Timing",
   "type": "timeseries",
   "description": "Shows the amount of time this node will wait for a response to a request before considering the request failed, and the average time it takes to get a response to a request.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "avalanche_requests_current_timeout{job=\"avalanchego\"}",
     "legendFormat": "Timeout {{node_id}}"
    },
    {
     "expr": "avalanche_requests_average_latency{job=\"avalanchego\"}",
     "legendFormat": "Response Time {{node_id}}"
    }
   ]
  },
  {
   "title": "Outstanding Requests",
   "type": "timeseries",
   "description": "Number of outstanding requests related to consensus/bootstrapping. Doesn't include handshake messages.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "expr": "avalanche_requests_outstanding{job=\"avalanchego\"}",
     "legendFormat": "Outstanding Requests {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_accepted_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_frontier_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_ancestors_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_put_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_multi_put_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_version_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_peerlist_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pull_query_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_push_query_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_version_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_ping_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pong_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_chits_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "app gossip {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_request_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_response_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "app response {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Sent per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_accepted_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_frontier_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_ancestors_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_put_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_multi_put_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_version_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_peerlist_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pull_query_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_push_query_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_version_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_ping_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pong_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_chits_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "app gossip {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_request_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_response_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "app response {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Received Bandwidth",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_accepted_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_frontier_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_ancestors_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_put_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_multi_put_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_version_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_peerlist_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pull_query_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_push_query_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_version_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_ping_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pong_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_chits_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "app gossip {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_request_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_response_received_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "app response {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Sent Bandwidth",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_accepted_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_frontier_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_ancestors_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_put_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_multi_put_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_version_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_peerlist_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pull_query_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_push_query_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_version_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_ping_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pong_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_chits_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "app gossip {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_request_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_response_sent_bytes{job=\"avalanchego\"}[1m])",
     "legendFormat": "app response {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Received Message Size",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_accepted_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_accepted_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_accepted_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_accepted_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_accepted_frontier_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_accepted_frontier_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_ancestors_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_ancestors_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_put_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_put_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_multi_put_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_multi_put_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_version_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_version_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_peerlist_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_peerlist_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_pull_query_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_pull_query_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_push_query_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_push_query_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_version_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_version_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "version {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_ping_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_ping_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_pong_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_pong_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_chits_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_chits_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_app_gossip_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_app_gossip_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "app gossip {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_app_request_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_app_request_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_app_response_received_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_app_response_received{job=\"avalanchego\"}[1m])",
     "legendFormat": "app response {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Sent Message Size",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_accepted_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_accepted_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_accepted_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_accepted_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_accepted_frontier_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_accepted_frontier_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_ancestors_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_ancestors_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_put_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_put_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_multi_put_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_multi_put_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_version_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_version_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_peerlist_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_peerlist_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_pull_query_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_pull_query_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_push_query_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_push_query_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_version_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_version_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "version {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_ping_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_ping_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_pong_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_pong_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_get_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_get_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_chits_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_chits_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_app_gossip_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_app_gossip_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "app gossip {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_app_request_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_app_request_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "increase(avalanche_network_app_response_sent_bytes{job=\"avalanchego\"}[1m])/increase(avalanche_network_app_response_sent{job=\"avalanchego\"}[1m])",
     "legendFormat": "app response {{node_id}}"
    }
   ]
  },
  {
   "title": "Queries Sent per Accepted Container",
   "type": "timeseries",
   "description": "Considers the X-Chain, P-Chain and C-Chain. A lower value indicates vote pipelining (good.) A higher value indicates failed polls (not good.)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expression": "($A + $B) / ($C + $D + $E)", "type": "math" }
   ]
  },
  {
   "title": "Messages Awaiting Send",
   "type": "timeseries",
   "description": "Number of messages that are queued to be sent to peers",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_awaiting_release{job=\"avalanchego\"}",
     "legendFormat": "Messages {{node_id}}"
    }
   ]
  },
  {
   "title": "Benched stake",
   "type": "timeseries",
   "description": "Amount of the stake in AVAX that is benched (ignored) because the nodes are unhealthy",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_X_benchlist_benched_weight{job=\"avalanchego\"}/1000000000",
     "legendFormat": "X chain {{node_id}}"
    },
    {
     "expr": "avalanche_P_benchlist_benched_weight{job=\"avalanchego\"}/1000000000",
     "legendFormat": "P Chain {{node_id}}"
    },
    {
     "expr": "avalanche_C_benchlist_benched_weight{job=\"avalanchego\"}/1000000000",
     "legendFormat": "C Chain {{node_id}}"
    }
   ]
  },
  { "title": "Inbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Inbound Byte Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_awaiting_acquire{job=\"avalanchego\"}",
     "legendFormat": "Messages Awaiting Acquire {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_remaining_validator_bytes{job=\"avalanchego\"}",
     "legendFormat": "Bytes Remaining {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire bytes from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_byte_throttler_inbound_acquire_latency_sum{job=\"avalanchego\"}[2m])/increase(avalanche_network_byte_throttler_inbound_acquire_latency_count{job=\"avalanchego\"}[2m])",
     "legendFormat": "Acquire {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Acquire Latency",
   "type": "timeseries",
   "description": "The amount of time, on average, that we wait to acquire from the throttler before reading a message.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(avalanche_network_buffer_throttler_inbound_acquire_latency_sum{job=\"avalanchego\"}[2m])/increase(avalanche_network_buffer_throttler_inbound_acquire_latency_count{job=\"avalanchego\"}[2m])",
     "legendFormat": "Acquire {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Awaiting Release (Messages Processing)",
   "type": "timeseries",
   "description": "Number of messages that are currently being handled and haven't yet returned their bytes to the inbound message throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 58 },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_awaiting_release{job=\"avalanchego\"}",
     "legendFormat": "Messages Awaiting Release {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Buffer Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire from the inbound message buffer throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 58 },
   "targets": [
    {
     "expr": "avalanche_network_buffer_throttler_inbound_awaiting_acquire{job=\"avalanchego\"}",
     "legendFormat": "Messages Awaiting {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Byte Throttler Remaining At-Large Bytes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the inbound message throttler",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_byte_throttler_inbound_remaining_at_large_bytes{job=\"avalanchego\"}",
     "legendFormat": "Remaining Bytes {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Bandwidth Throttler Awaiting Acquire",
   "type": "timeseries",
   "description": "Number of messages waiting to acquire bytes from the inbound bandwidth throttler.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 66 },
   "targets": [
    {
     "expr": "avalanche_network_bandwidth_throttler_inbound_awaiting_acquire{job=\"avalanchego\"}",
     "legendFormat": "Messages Awaiting Acquire {{node_id}}"
    }
   ]
  },
  { "title": "Outbound Throttling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Outbound Throttler Remaining At-Large Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the at-large byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_remaining_at_large_bytes{job=\"avalanchego\"}",
     "legendFormat": "Bytes Remaining {{node_id}}"
    }
   ]
  },
  {
   "title": "Outbound Throttler Remaining Validator Bytyes",
   "type": "timeseries",
   "description": "Number of bytes left in the validator byte allocation of the outbound message throttler",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avalanche_network_throttler_outbound_remaining_validator_bytes{job=\"avalanchego\"}",
     "legendFormat": "Bytes Remaining {{node_id}}"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Messages Failed To Send per Second",
   "type": "timeseries",
   "description": "From all chains",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_accepted_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_accepted_frontier_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get accepted frontier {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_ancestors_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_put_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_multi_put_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_version_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_get_peerlist_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "get peerlist {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pull_query_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_push_query_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_version_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "version {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_ping_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "ping {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_pong_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "pong {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_chits_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "app gossip {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_request_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_response_failed{job=\"avalanchego\"}[1m])",
     "legendFormat": "app response {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Failed To Parse per Minute",
   "type": "timeseries",
   "description": "Number of messages that could not be parsed because they were of unknown type or invalidly formatted.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "targets": [
    {
     "expr": "increase(avalanche_network_msgs_failed_to_parse{job=\"avalanchego\"}[1m])>0",
     "legendFormat": "Failed to Parse {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of inbound messages dropped (not processed) due to expiration in last minute.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": "increase(avalanche_P_handler_expired{job=\"avalanchego\"}[1m])+increase(avalanche_C_handler_expired{job=\"avalanchego\"}[1m])+increase(avalanche_X_handler_expired{job=\"avalanchego\"}[1m])",
     "legendFormat": "Messages Dropped {{node_id}}"
    }
   ]
  },
  {
   "title": "Outbound Messages Dropped in Last Minute",
   "type": "timeseries",
   "description": "Number of outbound messages dropped (not sent) due to rate-limiting in the last minute",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 92 },
   "targets": [
    {
     "expr": "increase(avalanche_network_throttler_outbound_acquire_failures{job=\"avalanchego\"}[1m])",
     "legendFormat": "Messages Dropped {{node_id}}"
    }
   ]
  },
  {
   "title": "Inbound Connections Dropped due to Rate-Limiting per Minute",
   "type": "timeseries",
   "description": "Number of inbound connections dropped due to inbound connection rate-limiting",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 92 },
   "targets": [
    {
     "expr": "increase(avalanche_network_inbound_conn_throttler_rate_limited{job=\"avalanchego\"}[1m])",
     "legendFormat": "Rate-Limited {{node_id}}"
    }
   ]
  },
  { "title": "Compression", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Average Message Compression Time (gzip codec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(increase(avalanche_network_codec_gzip_push_query_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_push_query_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Push Query {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_gzip_put_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_put_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Put {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_gzip_peerlist_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_peerlist_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Peer List {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_gzip_app_gossip_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_app_gossip_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Gossip {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_gzip_app_request_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_app_request_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Request {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_app_gzip_response_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_app_response_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Response {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Message Compression Time (gzip codec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(increase(avalanche_network_codec_gzip_push_query_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_push_query_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Push Query {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_gzip_put_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_put_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Put {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_gzip_peerlist_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_peerlist_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Peer List {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_gzip_app_gossip_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_app_gossip_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Gossip {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_gzip_app_request_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_app_request_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Request {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_app_gzip_response_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_gzip_app_response_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Response {{node_id}}"
    }
   ]
  },
  {
   "title": "Total Message Compression Time per Second (zstd codec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_codec_zstd_push_query_compress_time_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Push Query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_codec_zstd_put_compress_time_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_codec_zstd_peerlist_compress_time_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Peer List {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_codec_zstd_app_gossip_compress_time_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "App Gossip {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_codec_zstd_app_request_compress_time_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "App Request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_codec_zstd_app_response_compress_time_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "App Response {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Message Compression Time (zstd codec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "(increase(avalanche_network_codec_zstd_push_query_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_zstd_push_query_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Push Query {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_zstd_put_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_zstd_put_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Put {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_zstd_peerlist_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_zstd_peerlist_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "Peer List {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_zstd_app_gossip_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_zstd_app_gossip_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Gossip {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_zstd_app_request_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_zstd_app_request_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Request {{node_id}}"
    },
    {
     "expr": "(increase(avalanche_network_codec_app_zstd_response_compress_time_sum{job=\"avalanchego\"}[5m])+1)/(increase(avalanche_network_codec_zstd_app_response_compress_time_count{job=\"avalanchego\"}[5m])+1)",
     "legendFormat": "App Response {{node_id}}"
    }
   ]
  },
  {
   "title": "Bytes Saved by Compression",
   "type": "timeseries",
   "description": "Rate at which we save bytes (don't send/receive them over the network) by compressing messages/receiving compressed messages.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(avalanche_network_multi_put_compression_saved_received_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Inbound Multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_multi_put_compression_saved_sent_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Outbound Multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_put_compression_saved_received_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Inbound Put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_put_compression_saved_sent_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Outbound Put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_push_query_compression_saved_received_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Inbound Push Query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_push_query_compression_saved_sent_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Outbound Push Query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_peerlist_compression_saved_received_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Inbound Peer List {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_peerlist_compression_saved_sent_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Outbound Peer List {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_compression_saved_received_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Inbound App Gossip {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_gossip_compression_saved_sent_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Outbound App Gossip {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_request_compression_saved_received_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Inbound App Request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_request_compression_saved_sent_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Outbound App Request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_response_compression_saved_received_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Inbound App Response {{node_id}}"
    },
    {
     "expr": "rate(avalanche_network_app_response_compression_saved_sent_bytes_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "Outbound App Response {{node_id}}"
    }
   ]
  }
 ]
}