{
 "title": "Subnets",
 "tags": [ "Avalanche" ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "chain_id", "label": "Chain ID", "query": { "query": "metrics(avalanche_.*)" } },
   { "name": "filter", "label": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "Accepted Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_${chain_id}_blks_accepted_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Accepted {{node_id}}"
    }
   ]
  },
  {
   "title": "Rejected Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(avalanche_${chain_id}_blks_rejected_count{job=\"avalanchego\"}[1m]))>0",
     "legendFormat": "Rejected {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Block Acceptance Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${chain_id}_blks_accepted_sum{job=\"avalanchego\"}[5m]) / rate(avalanche_${chain_id}_blks_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "Avg Acceptance Latency {{node_id}}"
    }
   ]
  },
  {
   "title": "Average Block Rejection Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and rejection by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${chain_id}_blks_rejected_sum{job=\"avalanchego\"}[5m]) / rate(avalanche_${chain_id}_blks_rejected_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "Avg Rejection Latency {{node_id}}"
    }
   ]
  },
  {
   "title": "Processing Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_${chain_id}_blks_processing{job=\"avalanchego\"}>0",
     "legendFormat": "Transactions {{node_id}}"
    }
   ]
  },
  {
   "title": "Incomplete Polls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_${chain_id}_polls > 0"
    }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "timeseries",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the C-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${chain_id}_handler_pull_query_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_push_query_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_chits_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_accepted_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_put_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_multiput_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_ancestors_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_failed_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_query_failed_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "query failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_accepted_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_request_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_request_failed_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_response_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "app response {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_gossip_sum{job=\"avalanchego\"}[5m])",
     "legendFormat": "app gossip {{node_id}}"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "timeseries",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(avalanche_${chain_id}_handler_chits_count{job=\"avalanchego\"}[5m]) + 1) / (increase(avalanche_${chain_id}_handler_chits_count{job=\"avalanchego\"}[5m]) + increase(avalanche_${chain_id}_handler_query_failed_count{job=\"avalanchego\"}[5m]) + 1)",
     "legendFormat": "% Successful {{node_id}}"
    }
   ]
  },
  {
   "title": "Message Handling Time (per Message)",
   "type": "timeseries",
   "description": "Measures how long each kind of request on the C-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(avalanche_${chain_id}_handler_pull_query_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_pull_query_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_push_query_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_push_query_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_chits_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_chits_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_accepted_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_put_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_multiput_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_multi_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_ancestors_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_get_ancestors_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_failed_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_get_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_query_failed_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_query_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "query failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_accepted_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_get_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_ancestors_failed_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_get_ancestors_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_request_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_app_request_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_request_failed_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_app_request_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_response_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_app_response_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app response {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_gossip_sum{job=\"avalanchego\"}[5m])/rate(avalanche_${chain_id}_handler_app_gossip_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app gossip {{node_id}}"
    }
   ]
  },
  {
   "title": "Subnet weight benched",
   "type": "timeseries",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(avalanche_${chain_id}_benchlist_benched_weight{job=\"avalanchego\"}[15m]) / 10^9",
     "legendFormat": "AVAX Benched {{node_id}}"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "Measures how many of each kind of message are received per second on the C-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(avalanche_${chain_id}_handler_pull_query_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "pull query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_push_query_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "push query {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_chits_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "chits {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "put {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_multi_put_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "multiput {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_ancestors_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_query_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "query failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_accepted_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get accepted {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_get_ancestors_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "get ancestors failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_request_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_request_failed_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app request failed {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_response_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app response {{node_id}}"
    },
    {
     "expr": "rate(avalanche_${chain_id}_handler_app_gossip_count{job=\"avalanchego\"}[5m])",
     "legendFormat": "app gossip {{node_id}}"
    }
   ]
  },
  {
   "title": "Block ID Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the cache where the key is the byte representation of the block, and the value is the block's ID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(avalanche_${chain_id}_vm_rpcchainvm_bytes_to_id_cache_hit[5m])/(increase(avalanche_${chain_id}_vm_rpcchainvm_bytes_to_id_cache_hit[5m])+increase(avalanche_${chain_id}_vm_rpcchainvm_bytes_to_id_cache_miss[5m]))",
     "legendFormat": "Hit Rate {{node_id}}"
    }
   ]
  },
  {
   "title": "Missing Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the missing block cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "increase(avalanche_${chain_id}_vm_rpcchainvm_missing_cache_hit[5m])/(increase(avalanche_${chain_id}_vm_rpcchainvm_missing_cache_hit[5m])+increase(avalanche_${chain_id}_vm_rpcchainvm_missing_cache_miss[5m]))",
     "legendFormat": "Hit Rate {{node_id}}"
    }
   ]
  },
  {
   "title": "Decided Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the decided block cache",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "increase(avalanche_${chain_id}_vm_rpcchainvm_decided_cache_hit[5m])/(increase(avalanche_${chain_id}_vm_rpcchainvm_decided_cache_hit[5m])+increase(avalanche_${chain_id}_vm_rpcchainvm_decided_cache_miss[5m]))",
     "legendFormat": "Hit Rate {{node_id}}"
    }
   ]
  },
  {
   "title": "Unverified Block Cache Hit Rate",
   "type": "timeseries",
   "description": "Hit rate for the unverified block cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "increase(avalanche_${chain_id}_vm_rpcchainvm_unverified_cache_hit[5m])/(increase(avalanche_${chain_id}_vm_rpcchainvm_unverified_cache_hit[5m])+increase(avalanche_${chain_id}_vm_rpcchainvm_unverified_cache_miss[5m]))",
     "legendFormat": "Hit Rate {{node_id}}"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avalanche_${chain_id}_handler_unprocessed_msgs_len",
     "legendFormat": "Pending Messages {{node_id}}"
    }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(avalanche_${chain_id}_handler_expired[1m])",
     "legendFormat": "Expired {{node_id}}"
    }
   ]
  }
 ]
}